-- ------------------------------------------
-- Cancellazione tabelle precedenti
-- ------------------------------------------

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS TOPICS;
DROP TABLE IF EXISTS SUBTOPICS;
DROP TABLE IF EXISTS ARTICLES;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS COMMENTS_VOTES;
DROP TABLE IF EXISTS FORGOT_PASSWORD_TOKENS;

SET FOREIGN_KEY_CHECKS=1;

-- ------------------------------------------
-- Creazione Tabelle
-- ------------------------------------------

CREATE TABLE USERS(
    Email varchar(100) PRIMARY KEY,
    Nickname varchar(100) UNIQUE,
    Password varchar(255),
    Name varchar(100) NOT NULL,
    Surname varchar(100) NOT NULL,
    Banned BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE ROLES(
    RoleName varchar(100) PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE USER_ROLES(
    UserID varchar(100),
    RoleName varchar(100),
    FOREIGN KEY (UserID) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (RoleName) REFERENCES ROLES(RoleName) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (UserID,RoleName)
) ENGINE=InnoDB;

CREATE TABLE TOPICS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name varchar(100),
    Description MEDIUMTEXT,
    ImageLink varchar(255)
) ENGINE=InnoDB;

CREATE TABLE SUBTOPICS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title varchar(100),
    Description MEDIUMTEXT,
    TopicID INT,
    FOREIGN KEY (TopicID) REFERENCES TOPICS(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ARTICLES(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title varchar(100) NOT NULL,
    HTMLCode LONGTEXT NOT NULL,
    AuthorID varchar(100),
    SubtopicID INT,
    FOREIGN KEY (AuthorID) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (SubtopicID) REFERENCES SUBTOPICS(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE COMMENTS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Text LONGTEXT NOT NULL,
    Date DATETIME,
    AuthorID varchar(100),
    ArticleID INT,
    FOREIGN KEY (AuthorID) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ArticleID) REFERENCES ARTICLES(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE COMMENTS_VOTES(
    CommentID INT,
    AuthorID varchar(100),
    is_like BOOLEAN,
    FOREIGN KEY (CommentID) REFERENCES COMMENTS(Id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (AuthorID) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (CommentID,AuthorID)
) ENGINE=InnoDB;

CREATE TABLE FORGOT_PASSWORD_TOKENS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserID varchar(100),
    Token varchar(255),
    expireDate date,
    FOREIGN KEY (UserID) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
