SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS TOPICS;
DROP TABLE IF EXISTS SUBTOPICS;
DROP TABLE IF EXISTS ARTICLES;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS COMMENTS_VOTES;

SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE USERS(
    Email varchar(100) PRIMARY KEY,
    Nickname varchar(100) UNIQUE,
    Password varchar(255),
    Name varchar(100) NOT NULL,
    Surname varchar(100) NOT NULL,
    ProfilePic varchar(100)
) ENGINE=InnoDB;

CREATE TABLE ROLES(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    RoleName varchar(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE USER_ROLES(
    UserID varchar(100) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    RoleID INT REFERENCES ROLES(RoleID) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (UserID,RoleID)
) ENGINE=InnoDB;

CREATE TABLE TOPICS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name varchar(100),
    Image BLOB
) ENGINE=InnoDB;

CREATE TABLE SUBTOPICS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title varchar(100),
    TopicID INT REFERENCES TOPICS(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ARTICLES(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    HTMLCode LONGTEXT,
    AuthorID varchar(100) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    SubtopicID INT REFERENCES SUBTOPICS(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE COMMENTS(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Text LONGTEXT,
    AuthorID varchar(100) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    ArticleID INT REFERENCES ARTICLES(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE COMMENTS_VOTES(
    CommentID INT REFERENCES COMMENTS(Id) ON UPDATE CASCADE ON DELETE CASCADE,
    AuthorID varchar(100) REFERENCES USERS(Email) ON UPDATE CASCADE ON DELETE CASCADE,
    is_like BOOLEAN
) ENGINE=InnoDB;



